name: pullex
description: A customizable pull-to-refresh widget for Flutter, based on pull_to_refresh with enhancements and bugfixes.
version: 1.0.0

publish_to: https://pub.dev
publisher: drivecode.com.ua

homepage: https://github.com/drivecode-team/pullex
repository: https://github.com/drivecode-team/pullex
issue_tracker: https://github.com/drivecode-team/pullex/issues

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true